;设置规则标志位
;surge_ruleset=🛑拦截广告,https://raw.githubusercontent.com/RodmanWang/ad/master/ad.list
;surge_ruleset=🛑拦截广告,https://raw.githubusercontent.com/RodmanWang/openclash-rule/main/rule/AD-Keyword.list
;surge_ruleset=DIRECT,https://raw.githubusercontent.com/RodmanWang/openclash-rule/main/rule/Special.list
surge_ruleset=DIRECT,https://raw.githubusercontent.com/RodmanWang/openclash-rule/main/rule/User-agent.list
;surge_ruleset=🚀代理,https://raw.githubusercontent.com/RodmanWang/openclash-rule/main/rule/Abroad-DNS.list
;surge_ruleset=🖥谷歌商店,https://raw.githubusercontent.com/RodmanWang/openclash-rule/main/rule/GooglePlay.list
;surge_ruleset=🎥奈飞,https://raw.githubusercontent.com/RodmanWang/openclash-rule/main/rule/NF.list
;surge_ruleset=📺香港媒体,https://raw.githubusercontent.com/RodmanWang/openclash-rule/main/rule/HK-Media.list
;surge_ruleset=📺台湾媒体,https://raw.githubusercontent.com/RodmanWang/openclash-rule/main/rule/TW-Media.list
;surge_ruleset=📺日本媒体,https://raw.githubusercontent.com/RodmanWang/openclash-rule/main/rule/JP-Media.list
;surge_ruleset=📺韩国媒体,https://raw.githubusercontent.com/RodmanWang/openclash-rule/main/rule/KR-Media.list
;surge_ruleset=📺美国媒体,https://raw.githubusercontent.com/RodmanWang/openclash-rule/main/rule/US-Media.list
;surge_ruleset=📺欧洲媒体,https://raw.githubusercontent.com/RodmanWang/openclash-rule/main/rule/EU-Media.list
;surge_ruleset=🇨🇳 台湾,https://raw.githubusercontent.com/RodmanWang/openclash-rule/main/rule/TW-Media.list
;surge_ruleset=🇯🇵 日本,https://raw.githubusercontent.com/RodmanWang/openclash-rule/main/rule/JP-Media.list
;surge_ruleset=🇰🇷 韩国,https://raw.githubusercontent.com/RodmanWang/openclash-rule/main/rule/KR-Media.list
;surge_ruleset=🇪🇺 欧洲,https://raw.githubusercontent.com/RodmanWang/openclash-rule/main/rule/EU-Media.list
;surge_ruleset=🚀代理,https://raw.githubusercontent.com/RodmanWang/openclash-rule/main/rule/Proxy-Domain.list
;surge_ruleset=DIRECT,https://raw.githubusercontent.com/RodmanWang/openclash-rule/main/rule/Domestic-Domain.list
;surge_ruleset=🚀代理,https://raw.githubusercontent.com/RodmanWang/openclash-rule/main/rule/Proxy-IP.list
;surge_ruleset=DIRECT,https://raw.githubusercontent.com/RodmanWang/openclash-rule/main/rule/Domestic-IP.list
;surge_ruleset=DIRECT,https://raw.githubusercontent.com/RodmanWang/openclash-rule/main/rule/China-IP.list
;surge_ruleset=DIRECT,[]GEOIP,CN
;surge_ruleset=🎮游戏,https://raw.githubusercontent.com/RodmanWang/openclash-rule/main/rule/game/Steam-Community.list
;surge_ruleset=🎮游戏,https://raw.githubusercontent.com/RodmanWang/openclash-rule/main/rule/game/NBA2K.list
;surge_ruleset=🎮游戏,https://raw.githubusercontent.com/RodmanWang/openclash-rule/main/rule/game/PUBG-Asia.list
surge_ruleset=DIRECT,[]FINAL
;设置规则标志位

;设置分组标志位
;注意字母大小写有区别
custom_proxy_group=🚀代理`select`[]🤸‍♂️故障转移`[]👋手动`[]🇭🇰 香港`[]🇨🇳 台湾`[]🇸🇬 新加坡`[]🇯🇵 日本`[]🇰🇷 韩国`[]🇺🇲 美国
custom_proxy_group=🎮游戏`select`(TW)`[]🚀代理`[]👋手动
custom_proxy_group=🎥奈飞`select`(NF\*)`[]👋手动
custom_proxy_group=📺美国媒体`select`(US.*NF\*)`[]👋手动
custom_proxy_group=📺欧洲媒体`select`[]🇪🇺 欧洲`[]📺美国媒体`[]👋手动
custom_proxy_group=📺香港媒体`select`([3-4]2[8-9])`[]👋手动
custom_proxy_group=📺台湾媒体`select`[]🇨🇳 台湾`[]🚀代理`[]👋手动
custom_proxy_group=📺日本媒体`select`[]🇯🇵 日本`[]🚀代理`[]👋手动
custom_proxy_group=📺韩国媒体`select`[]🇰🇷 韩国`[]🚀代理`[]👋手动
custom_proxy_group=🖥谷歌商店`select`[]🇺🇲 美国`[]👋手动
custom_proxy_group=🇭🇰 香港`select`(港|HK)
custom_proxy_group=🇨🇳 台湾`select`(台|新北|彰化|TW|Tai)
custom_proxy_group=🇸🇬 新加坡`select`(新|狮城|SG|Singa)
custom_proxy_group=🇯🇵 日本`select`(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Jap)
custom_proxy_group=🇰🇷 韩国`select`(韩国|首尔|KR)
custom_proxy_group=🇺🇲 美国`select`(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US)
custom_proxy_group=🇪🇺 欧洲`select`(英|德|意|法|伦敦|DE|GB|IT|FR)
custom_proxy_group=🤸‍♂️故障转移`fallback`(402|412|508)`http://www.gstatic.com/generate_204`10800
custom_proxy_group=👋手动`select`.*
custom_proxy_group=🛑拦截广告`select`[]REJECT`[]DIRECT
;fallback输入你常用的2-3个节点编号
;设置分组标志位
