surge_ruleset=DIRECT,https://raw.githubusercontent.com/RodmanWang/openclash-rule/main/list/User·agent.list
surge_ruleset=DIRECT,[]GEOIP,CN
surge_ruleset=🐟Other,[]FINAL

;字母大小写有区别
custom_proxy_group=🚀Proxy`select`[]🚀AutoProxy`[]👋Manual
custom_proxy_group=🎮Game`select`[]🎮Game·Auto`[]👋Manual
custom_proxy_group=🎥Netflix`select`[]🎞NF·Auto`[]👋Manual
custom_proxy_group=🎥Youtube`select`[]🎞Youtu·Auto`[]👋Manual
custom_proxy_group=🎥General·Media`select`[]🎞Media·Auto`[]👋Manual
custom_proxy_group=📺US·Media`select`[]🎞US·Auto`[]👋Manual
custom_proxy_group=📺HK·Media`select`[]🎞TVB·Auto`[]👋Manual
custom_proxy_group=📺EUR·Media`select`[]🎥General·Media`[]EUR 🇪🇺`[]👋Manual
custom_proxy_group=📺TW·Media`select`[]🎥General·Media`[]TW 🇨🇳`[]👋Manual
custom_proxy_group=📺JP·Media`select`[]🎥General·Media`[]JP 🇯🇵`[]👋Manual
custom_proxy_group=📺KR·Media`select`[]🎥General·Media`[]KR 🇰🇷`[]👋Manual
custom_proxy_group=💻Microsoft`select`[]DIRECT`[]🚀Proxy`[]👋Manual
custom_proxy_group=🍎Apple`select`[]DIRECT`[]🚀Proxy
custom_proxy_group=🐟Other`select`[]🚀Proxy`[]DIRECT
custom_proxy_group=⛔AD·Block`select`[]REJECT`[]DIRECT
custom_proxy_group=🚀AutoProxy`url-test`(42[79]|(京L06|港HE05|港A02)S2.*IEPL|港HE02S2.*高防|京L0[56]S1|Vio|港.*电|Geneva)`http://www.gstatic.com/generate_204`600
custom_proxy_group=🎮Game·Auto`url-test`((京L06|港HE05|港A02)S2.*IEPL|港HE02S2.*高防|京L0[56]S1|Vio|Geneva)`http://www.gstatic.com/generate_204`6000
custom_proxy_group=🎞NF·Auto`url-test`([012][UT].*SG.*NF\*|狮.*[电石])`http://www.gstatic.com/generate_204`6000
custom_proxy_group=🎞Youtu·Auto`url-test`(4(34|51)|美.*0[35]|台.*[郑津石]|Vio|Geneva)`http://www.gstatic.com/generate_204`6000
custom_proxy_group=🎞Media·Auto`url-test`(4(34|51)|美.*0[35]|港.*电|Vio|Geneva)`http://www.gstatic.com/generate_204`6000
custom_proxy_group=🎞TVB·Auto`url-test`(港.*[电郑]|DMIT)`http://www.gstatic.com/generate_204`6000
custom_proxy_group=🎞US·Auto`url-test`(US.*NBU\*|Vio)`http://www.gstatic.com/generate_204`6000
custom_proxy_group=👋Manual`select`.*
custom_proxy_group=HK 🇭🇰`select`(港|HK)
custom_proxy_group=TW 🇨🇳`select`(台|新北|彰化|TW|Tai)
custom_proxy_group=SG 🇸🇬`select`(新|狮城|SG|Singa)
custom_proxy_group=JP 🇯🇵`select`(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Jap)
custom_proxy_group=KR 🇰🇷`select`(韩国|首尔|KR)
custom_proxy_group=US 🇺🇲`select`(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US)
custom_proxy_group=EUR 🇪🇺`select`(英|德|意|法|伦敦|DE|GB|IT$|FR|RO|NL|UK|CH)
