;规则标志位
;surge_ruleset=⛔AD·Blockhttps://raw.githubusercontent.com/RodmanWang/ad/master/ad.list
;surge_ruleset=⛔AD·Block,https://raw.githubusercontent.com/RodmanWang/openclash-rule/main/rule/AD·custom.list
;surge_ruleset=DIRECT,https://raw.githubusercontent.com/RodmanWang/openclash-rule/main/rule/Special.list
surge_ruleset=DIRECT,https://raw.githubusercontent.com/RodmanWang/openclash-rule/main/rule/User·agent.list
;surge_ruleset=📺US·Media,https://raw.githubusercontent.com/RodmanWang/openclash-rule/main/rule/US·Media.list
;surge_ruleset=📺EUR·Media,https://raw.githubusercontent.com/RodmanWang/openclash-rule/main/rule/EUR·Media.list
;surge_ruleset=📺HK·Media,https://raw.githubusercontent.com/RodmanWang/openclash-rule/main/rule/HK·Media.list
;surge_ruleset=📺TW·Media,https://raw.githubusercontent.com/RodmanWang/openclash-rule/main/rule/TW·Media.list
;surge_ruleset=📺JP·Media,https://raw.githubusercontent.com/RodmanWang/openclash-rule/main/rule/JP·Media.list
;surge_ruleset=📺KR·Media,https://raw.githubusercontent.com/RodmanWang/openclash-rule/main/rule/KR·Media.list
;surge_ruleset=🎥Netflix,https://raw.githubusercontent.com/RodmanWang/openclash-rule/main/rule/NF.list
;surge_ruleset=🎥General·Media,https://raw.githubusercontent.com/RodmanWang/openclash-rule/main/rule/General·Media.list
;surge_ruleset=🚀Proxy,https://raw.githubusercontent.com/RodmanWang/openclash-rule/main/rule/Proxy·Domain.list
;surge_ruleset=DIRECT,https://raw.githubusercontent.com/RodmanWang/openclash-rule/main/rule/Domestic·Domain.list
surge_ruleset=DIRECT,[]GEOIP,CN
;surge_ruleset=💻Microsoft,https://raw.githubusercontent.com/RodmanWang/openclash-rule/main/rule/game/Microsoft.list
;surge_ruleset=🎮Game,https://raw.githubusercontent.com/RodmanWang/openclash-rule/main/rule/game/Steam·Community.list
;surge_ruleset=🎮Game,https://raw.githubusercontent.com/RodmanWang/openclash-rule/main/rule/game/NBA2K.list
;surge_ruleset=🎮Game,https://raw.githubusercontent.com/RodmanWang/openclash-rule/main/rule/game/PUBG·Asia.list
surge_ruleset=🐟Other,[]FINAL
;规则标志位

;分组标志位
;字母大小写有区别
custom_proxy_group=🚀Proxy`select`[]🚀Auto·Proxy·Test`[]👋Manual
custom_proxy_group=🎮Game`select`[]🚀Proxy`[]👋Manual
custom_proxy_group=🎥Netflix`select`[]🎞NF·Proxy·Test`[]👋Manual
custom_proxy_group=🎥General·Media`select`[]🎞Media·Proxy·Test`[]👋Manual
custom_proxy_group=📺US·Media`select`[]🎞Media·Proxy·Test`(US.*NBU\*)
custom_proxy_group=📺EUR·Media`select`[]🎞Media·Proxy·Test`[]EUR 🇪🇺`[]📺US·Media
custom_proxy_group=📺HK·Media`select`(42[0-2])`[]🎞Media·Proxy·Test
custom_proxy_group=📺TW·Media`select`[]🎞Media·Proxy·Test`[]TW 🇨🇳
custom_proxy_group=📺JP·Media`select`[]🎞Media·Proxy·Test`[]JP 🇯🇵
custom_proxy_group=📺KR·Media`select`[]🎞Media·Proxy·Test`[]KR 🇰🇷
custom_proxy_group=💻Microsoft`select`[]DIRECT`[]🚀Proxy
custom_proxy_group=🐟Other`select`[]🚀Proxy`[]DIRECT
custom_proxy_group=⛔AD·Block`select`[]REJECT`[]DIRECT
custom_proxy_group=👋Manual`select`.*
custom_proxy_group=🚀Auto·Proxy·Test`url-test`(4(2[36])|72)`http://www.gstatic.com/generate_204`600
custom_proxy_group=🎞NF·Proxy·Test`url-test`(1x.*SG.*NF\*)`http://www.gstatic.com/generate_204`6000
custom_proxy_group=🎞Media·Proxy·Test`url-test`([13579][UT].*1x.*HK)`http://www.gstatic.com/generate_204`6000
custom_proxy_group=HK 🇭🇰`select`(港|HK)
custom_proxy_group=TW 🇨🇳`select`(台|新北|彰化|TW|Tai)
custom_proxy_group=SG 🇸🇬`select`(新|狮城|SG|Singa)
custom_proxy_group=JP 🇯🇵`select`(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Jap)
custom_proxy_group=KR 🇰🇷`select`(韩国|首尔|KR)
custom_proxy_group=US 🇺🇲`select`(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US)
custom_proxy_group=EUR 🇪🇺`select`(英|德|意|法|伦敦|DE|GB|IT|FR)
;fallback输入常用的节点编号
;分组标志位
