name: Update
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - "**/README.md"
jobs:
  build:
    name: Generate GeoIP2 database
    runs-on: ubuntu-latest
    steps:
        
    - name: Push artifacts to release branch
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git reset --hard HEAD
        git fetch
        git checkout release
        
        git checkout --orphan release-orphan
        git rm -rf .
        
        cp -rf rule-provider/Apple.yaml ./
        cp -rf rule-provider/Domestic.yaml ./
        cp -rf rule-provider/Domestic·IP.yaml ./
        cp -rf rule-provider/EUR·Media.yaml ./
        cp -rf rule-provider/Game.yaml ./
        cp -rf rule-provider/Generally·Media.yaml ./
        cp -rf rule-provider/HK·Media.yaml ./
        cp -rf rule-provider/JP·Media.yaml ./
        cp -rf rule-provider/KR·Media.yaml ./
        cp -rf rule-provider/Microsoft.yaml ./
        cp -rf rule-provider/Netflix.yaml ./
        cp -rf rule-provider/OpenAI.yaml ./
        cp -rf rule-provider/PayPal.yaml ./
        cp -rf rule-provider/Proxy.yaml ./
        cp -rf rule-provider/Proxy·IP.yaml ./
        cp -rf rule-provider/Special.yaml ./
        cp -rf rule-provider/TW·Media.yaml ./
        cp -rf rule-provider/Telegram.yaml ./
        cp -rf rule-provider/Test.yaml ./
        cp -rf rule-provider/US·Media.yaml ./

        git add Apple.yaml
        git add Domestic.yaml
        git add Domestic·IP.yaml
        git add EUR·Media.yaml
        git add Game.yaml
        git add Generally·Media.yaml
        git add HK·Media.yaml
        git add JP·Media.yaml
        git add KR·Media.yaml
        git add Microsoft.yaml
        git add Netflix.yaml
        git add OpenAI.yaml
        git add PayPal.yaml
        git add Proxy.yaml
        git add Proxy·IP.yaml
        git add Special.yaml
        git add TW·Media.yaml
        git add Telegram.yaml
        git add Test.yaml
        git add US·Media.yaml

        
        git commit -m "update : $(TZ=UTC-8 date "+%Y-%m-%d %H:%M:%S")"
        git branch -D release
        git branch -m release
            
    - name: GitHub Push
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.PERSON_TOKEN }}
        branch: release
        force: true
        
    - name: Delete workflow
      uses: Mattraks/delete-workflow-runs@v2
      with:
        retain_days: 1
        keep_minimum_runs: 3
